// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace PersonDirectory.Persistence.Models
{
    public partial class City
    {
        public City()
        {
            People = new HashSet<Person>();
        }

        public int Id { get; set; }

        [Column("City")]
        public string Name { get; set; }
        public string Country { get; set; }

        public virtual ICollection<Person> People { get; set; }
    }
}