// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace PersonDirectory.Domain.Models
{
    public class PhoneNumber
    {
        public int Id { get; set; }

        public PhoneNumberType NumberType { get; set; }
        
        [StringLength(maximumLength: 50, MinimumLength = 4)]
        public string Number { get; set; }

        public int PersonId { get; set; }
    }
}