// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Repository.Models
{
    public partial class City
    {
        public City()
        {
            People = new HashSet<Person>();
        }

        public int Id { get; set; }
        public string City1 { get; set; }
        public string Country { get; set; }

        public virtual ICollection<Person> People { get; set; }
    }
}