// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PersonDirectory.Persistence.Models
{
    public partial class Person
    {
        public Person()
        {
            PhoneNumbers = new HashSet<PhoneNumber>();
            RelationPeople = new HashSet<Relation>();
            RelationRelatedPeople = new HashSet<Relation>();
        }

        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Gender? Gender { get; set; }
        public string PersonalNumber { get; set; }
        public DateTime DateOfBirth { get; set; }
        public int? CityId { get; set; }
        public string Photo { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
        public virtual ICollection<Relation> RelationPeople { get; set; }
        public virtual ICollection<Relation> RelationRelatedPeople { get; set; }
    }

    public enum Gender
    {
        Female = 1,
        Male = 2
    }
}