// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Repository.Models
{
    public partial class PhoneNumber
    {
        public int Id { get; set; }
        public string PhoneNumberType { get; set; }
        public string PhoneNumber1 { get; set; }
        public int PersonId { get; set; }

        public virtual Person Person { get; set; }
    }
}