// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using PersonDirectory.Domain.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace PersonDirectory.Persistence.Models
{
    public partial class PhoneNumber
    {
        public int Id { get; set; }
        public PhoneNumberType PhoneNumberType { get; set; }

        [Column("PhoneNumber")]
        public string Number { get; set; }
        public int PersonId { get; set; }

        public virtual Person Person { get; set; }
    }
}