// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Repository.Models
{
    public partial class Relation
    {
        public int PersonOne { get; set; }
        public int PersonTwo { get; set; }
        public Relations RelationId { get; set; }

        public virtual Person PersonOneNavigation { get; set; }
        public virtual Person PersonTwoNavigation { get; set; }
    }

    public enum Relations : byte
    {
        Coleague = 1,
        Familiar = 2,
        Relative = 3,
        Other = 4
    }
}