// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using PersonDirectory.Domain.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace PersonDirectory.Persistence.Models
{
    public partial class Relation
    {
        public int PersonId { get; set; }
        public int RelatedPersonId { get; set; }
        public RelationType RelationId { get; set; }

        public virtual Person Person { get; set; }
        public virtual Person RelatedPerson { get; set; }
    }
}